language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+$/"
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'
before_script:
- composer install
script:
- composer test
before_deploy:
  - echo 'Making deploy packages...'
  - rm -rfv .git
  - rm -rfv bin
  - rm -rfv tests
  - rm -rfv .gitignore
  - rm -rfv .travis.yml
  - rm -rfv vendor
  - rm -rfv composer.lock
  - rm -rfv phpunit.xml.dist
  - zip -r string-utility.zip ./
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: bOP37wcXIZgFss+/SWi4zLmRlSMJ36eDqBQySKIm78mHaEYzd7HCQILjvhdExXwVRoE/e0WhecHZzjKRBlw2+DLXFfWKyGtiMAblUBYSMSJTliGqtUwjrEyhR/7tWhPh9edRPnPUCVft2hepHAc5P2piLwEO4JINmyxBoYJb6Ttn1z1V+N6XMKi7QPEuKTC3MX8woTKvaxmzGVKkgBYRLwk/x3AJzl0qs0JdhFFez9Q262RI5boDf7mH2AnaKiJLX8NhZ3k7d9TDj5x6BP51ZGYFrIRpscW8OC/fbbb9o3LaaqDm6Ub4CVGESxP0RnsE8Hvn4DW6UpRXNRuw5pPu4AFl2k7s+3IHNUSlvCfNAkjxkgrxLO3MnEoPgayxsZ+/YjW3ikwFd6BWe13i44qBw2cOpd/ufIJbTFKz6+fFaqoUJZ6F+iBjkVgbPYcdrF7TVz7YMsmjzudsG0wG6V2PE1VkOxNbp+seaPLbyd4LLzSGVqXx0Flc/h+1Tff1mk/+X2r4T3wEjeYJ28VzZeK3y+N2lzfADg5Qg81rte0WC7v9lOUetFpb8JL/uCYvhyqym6bkyKhcnMrXLH0B+T0ma+yGHylbyEC90ui9ntOitJX52lBs/kgHXyLQhGLS3K3VWT96b9sMWgcQMOPMRd1/Qide+i8PTvtwTiE7ZHwD694=
  file: string-utility.zip
  on:
    repo: hametuha/string-utility
    tags: true
    php: '7.0'
